### ISSUE TITLE
Link going back to docs.racksapce.com instead of developer

### ISSUE THREAD

**Issue by lauracly** [rackerlabs/docs-cloud-databases#10]
Link going to docs instead of developer: Under Create Backup, 1st note, here is the Delete Backup:
http://docs.rackspace.com/cdb/api/v1.0/cdb-devguide/content/DELETE_deleteBackup__version___accountId__backups__backupId__backups.html

There are 3 of them in this chunk.

**Comment by masthalter** [comment]
Fixed links.
