### ISSUE TITLE
Edits for release notes

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-cloud-databases#13]
See the markup and comments in the attached Word doc for my suggested edits for the release notes. Please let me know if you have any questions. Thanks!
 
[Cloud Databases Release Notes_editsKH.docx](https://github.com/rackerlabs/docs-cloud-databases/files/30359/Cloud.Databases.Release.Notes_editsKH.docx)

**Comment by masthalter** [comment]
I integrated your comments to the DB Release Notes.

Thanks!

Mike
