### ISSUE TITLE
Structure for databased GS content added

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-databases#15]
Hi Mike,

Thought it would be helpful to provide an overview of the GS file structure so that you can find the use cases overviews and examples more easily.  Here's the tree structure with note about changes:
├── getting-started
│   ├── access-database-instance.rst -- *Overview topic includes Create server, configure app, admin*
│   ├── authenticate.rst -- *Common authentication topic*
│   ├── backup-database-instances.rst  *Overview topic includes examples/backup-db-examples.rst
│   ├── create-use-database.rst  *Overview topic includes  examples/create db, list db, list db users
│   ├── examples
│   │   ├── backup-db-examples.rst
│   │   ├── check-server-time-mysql.rst
│   │   ├── create-db-instance.rst
│   │   ├── list-dbs-in-dbinstance.rst
│   │   ├── list-flavors.rst
│   │   ├── list-users-in-dbinstance.rst
│   │   ├── manage-tz-curl.rst
│   │   ├── manage-tz-trove.rst
│   ├── index.rst
│   ├── manage-tz-ovw.rst   *Time zone overview includes examples manage-tz trove, curl, check time*
│   ├── prerequisites-for-using-api.rst  *Common prerequisites topic*
│  └── send-request-ovw.rst    *Common send API requests topic*
├── getting-started.rst   *Getting started H1 page*
├── index.rst   *Updated index.rst with Getting started topics added*

**Comment by masthalter** [comment]
I removed the file setup-gui-client.rst from the examples, since it was not actually being used. The content for the Admin topic is actually in the file access-database-instance.rst.
