### ISSUE TITLE
Internal doc migration

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-databases#27]
Determine whether the [Cloud Databases Admin Developer Guide](http://docs-internal.rackspace.com/cdb/api/v1.0/cdb-mgmt-devguide/content/overview.html) needs to be migrated from docs-internal.rackspace.com website to the new docs-internal landing page.   

If migration is required, store last PDF in CDN-enabled Cloud Files container and add link to new internal landing page.

**Comment by meker12** [comment]
Sent e-mail to team.

**Comment by meker12** [comment]
Follow up with Dev team. No response to Monday e-mail about whether internal docs can be retired. @cyrichardson Have you heard anything?

**Comment by cyrichardson** [comment]
@meker12 I haven't heard anything.

**Comment by meker12** [comment]
Closing this issue. If the internal docs for Cloud databases need to be migrated, please open a new issue.  Thanks!
