### ISSUE TITLE
Missing code in configuring environment variables

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/docs-cloud-databases#33]
From: Aaron Mittag <Aaron.Mittag@rackspace.com>
Date: Tuesday, March 15, 2016 at 9:29 PM
To: "how-to@rackspace.com" <How-To@rackspace.com>
Cc: Paul Widsten <paul.widsten@rackspace.com>
Subject: Guide Update

Hello,

I've come across a guide that's missing a bit of information should a customer copy paste it, there's an additional line needed here.

Under "Configure environment variables for client" on
https://developer.rackspace.com/docs/cloud-databases/v1/developer-guide/#id6

Current:
```
export OS_AUTH_URL=https://identity.api.rackspacecloud.com/v2.0/
export OS_USERNAME=yourUserName
export OS_TENANT_ID=yourTenantId
export OS_REGION_NAME=yourRegionName
export OS_PASSWORD=yourPassword
```

Should be:
```
export OS_AUTH_URL=https://identity.api.rackspacecloud.com/v2.0/
export OS_USERNAME=yourUserName
export OS_TENANT_ID=yourTenantId
export OS_REGION_NAME=yourRegionName
export OS_PASSWORD=yourPassword

export TROVE_SERVICE_TYPE=rax:database
```

Thanks!

Aaron Mittag
Linux Administrator I

aaron.mittag@rackspace.com

**Comment by kylelaffoon** [comment]
Sent note to Aaron requesting review on PR https://github.com/kylelaffoon/docs-cloud-databases/pull/1 for technical review.

**Comment by kylelaffoon** [comment]
This is now corrected.
