### ISSUE TITLE
Trove Client Setup Incorrectly Labeled For OSX

### ISSUE THREAD

**Issue by corbanCloud** [rackerlabs/docs-cloud-databases#39]
https://developer.rackspace.com/docs/cloud-databases/v1/developer-guide/#install-the-trove-client

Section reads: 

> For Ubuntu, Debian, or OS X:
> 
> $ sudo apt-get install python2.7-dev
> 
> $ sudo pip install python-troveclient

apt-get is not available on OSX, homebrew is one of the more popular package managers for OS. See http://brew.sh/ for more info.

consider offering the following command for OSX, which will install python @ 2.7.11
>$ brew install python

**Comment by kylelaffoon** [comment]
@riddhi89 Would this be an acceptable option to include in this article? If so, I can get it implemented.
