### ISSUE TITLE
Frontend javascript performance is really bad

### ISSUE THREAD

**Issue by blasto333** [rackerlabs/docs-cloud-databases#52]
https://developer.rackspace.com/docs/cloud-databases/v1/developer-guide/#document-index

crashes on iPad; really slow on desktop

**Comment by meker12** [comment]
@blasto33 We are in the process of restructuring the content so that everthing does not load in a single page.  Will update this issue when work is complete to see if the content is more responsive.  Thanks for reporting the issue.

**Comment by blasto333** [comment]
@meker12 Thanks!

**Comment by catlook** [comment]
The change that Margaret described was implemented almost 2 years ago.  In our experience, performance is much improved.  Let us know if you still have problems, @blasto333.
