### ISSUE TITLE
Which datastore types support Schedule Backups?

### ISSUE THREAD

**Issue by joeashcraft** [rackerlabs/docs-cloud-databases#67]
For Scheduled Backups, [our docs](https://developer.rackspace.com/docs/cloud-databases/v1/api-reference/automated-backups/) state "Supported datastore versions for HA are MySQL 5.6, Percona 5.6, and MariaDB 10."

This is a valid statement regarding HA groups, and the statement already appears (verbatim) in the [HA docs](https://developer.rackspace.com/docs/cloud-databases/v1/api-reference/ha/).

This statement should instead clarify which datastore types allow Scheduled Backups.

**Comment by meker12** [comment]
@joeashcraft  I updated the text to replace "HA" with "Scheduled Backups".  Please review PR #68.  Thanks!

**Comment by joeashcraft** [comment]
Thanks, @meker12!

I'm not the authority on which datastore version are supported with Scheduled Backups. Our [Knowledge Center says](https://support.rackspace.com/how-to/scheduled-backups-for-cloud-databases/) "MySQL 5.6, Percona 5.6, and MariaDB 10 or later". Maybe someone from our datastores team could confirm this for us...

**Comment by meker12** [comment]
That article was audited 9/13/2016.  The update matches, so will go ahead and merge the change. Thanks!
